appVersion: latest
image: ghcr.io/preparingforexams/telegram-vreddit-bot

isEnabled: true

features:
  - handle_updates
  - download
  - youtube_url_convert
  - telegram_audio_convert
  - twitter_download
  - vimeo_download
  - youtube_download
  - insta_download

scratch:
  storageclass: longhorn-temp
  size: 2Gi
