appVersion: latest
image: ghcr.io/preparingforexams/telegram-vreddit-bot

isEnabled: true

defaultResources:
  limits:
    cpu: 800m
  requests:
    cpu: 50m
    memory: 128Mi

nats:
  monitorEndpoint: "nats-headless.nats-system.svc.cluster.local:8222"
  consumerUrl: "nats://nats.nats-system.svc.cluster.local:4222"
  streamName: cancers

subscribers:
  generic-downloader:
    kedaConsumer: download
    args:
      - download
    enableScratchSpace: true
    env:
      DOWNLOAD_TYPE: download
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 512Mi
  telegram-audio:
    kedaConsumer: voice-download
    args:
      - telegram-audio-convert
    enableScratchSpace: true
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 10m
        memory: 128Mi
  tiktok:
    kedaConsumer: tiktok-download
    args:
      - download
    enableScratchSpace: true
    env:
      DOWNLOAD_TYPE: tiktok-download
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 512Mi
  url-alias:
    args:
      - url-alias-resolution
  vimeo:
    kedaConsumer: vimeo-download
    args:
      - download
    enableScratchSpace: true
    env:
      DOWNLOAD_TYPE: vimeo-download
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: "2"
        memory: 512Mi
  youtube-converter:
    args:
      - youtube-url-convert
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 10m
        memory: 128Mi
  youtube-downloader:
    kedaConsumer: youtube-download
    args:
      - download
    enableScratchSpace: true
    env:
      DOWNLOAD_TYPE: youtube-download
    resources:
      limits:
        cpu: "2"
        memory: 512Mi
      requests:
        cpu: "2"
        memory: 512Mi

scratch:
  storageclass: longhorn-temp
  size: 2Gi
