---
apiVersion: v1
kind: Service
metadata:
  name: cancer-insta
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cancer-insta-downloader
spec:
  revisionHistoryLimit: 0
  serviceName: cancer-insta
  selector:
    matchLabels:
      app: insta-downloader
  replicas: {{ if .Values.isEnabled }}1{{ else }}0{{ end }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cookie-jar
      spec:
        storageClassName: longhorn-crypto
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
  template:
    metadata:
      labels:
        app: insta-downloader
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - download
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: "2"
              memory: 512Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
            - name: DOWNLOAD_TYPE
              value: insta-download
            - name: COOKIE_FILE
              value: /cookies/insta-cookies.dat
          envFrom:
            - secretRef:
                name: base
            - secretRef:
                name: nats
          volumeMounts:
            - mountPath: "/downloads"
              name: downloads
            - mountPath: "/cookies"
              name: cookie-jar
            - mountPath: "/static-cookies"
              name: cookie
      volumes:
        - {{ include "downloads.volume" $ | fromYaml | toJson }}
        - name: cookie
          secret:
            secretName: insta-cookies
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cancer-insta-downloader
spec:
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: cancer-insta-downloader
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: {{ $.Values.nats.monitorEndpoint | quote }}
        account: "$G"
        stream: {{ $.Values.nats.streamName | quote }}
        consumer: insta-download
