{{ if has "insta_download" .Values.features  }}
---
apiVersion: v1
kind: Service
metadata:
  name: cancer-insta
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cancer-insta-downloader
spec:
  revisionHistoryLimit: 0
  serviceName: cancer-insta
  selector:
    matchLabels:
      app: insta-downloader
  replicas: {{ if .Values.isEnabled }}1{{ else }}0{{ end }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cookie-jar
      spec:
        storageClassName: longhorn-crypto
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
  template:
    metadata:
      labels:
        app: insta-downloader
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - download
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
            - name: DOWNLOAD_TYPE
              value: insta
            - name: COOKIE_FILE
              value: /cookies/insta-cookies.dat
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: base
          volumeMounts:
            - {{ include "secrets.volumeMount" . | fromYaml | toJson }}
            - mountPath: "/downloads"
              name: downloads
            - mountPath: "/cookies"
              name: cookie-jar
            - mountPath: "/static-cookies"
              name: cookie
      volumes:
        - {{ include "downloads.volume" $ | fromYaml | toJson }}
        - {{ include "secrets.volume" $ | fromYaml | toJson }}
        - name: cookie
          secret:
            secretName: insta-cookies
{{ end }}
