---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insta-cookies
spec:
  # 14 days
  refreshInterval: "336h"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  data:
    - secretKey: insta-cookies.dat
      remoteRef:
        key: "name:insta-cookies"
        decodingStrategy: None
