---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:nats"
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.+)"
            target: "NATS_$1"
