---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gsa
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  data:
    - secretKey: gsa.json
      remoteRef:
        key: "name:gsa-json"
        decodingStrategy: None
