---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insta-credentials
spec:
  refreshInterval: "7d"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:insta-credentials"
