{{- if .Values.useScalewayNats }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:nats"
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.+)"
            target: "NATS_CANCER_$1"
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nats
stringData:
  NATS_CANCER_ENDPOINT: "nats://nats.nats-system:4222"
  NATS_CANCER_STREAM_NAME: "cancers"
{{- end }}
