---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: insta-credentials
spec:
  # 7 days
  refreshInterval: "168h"
  secretStoreRef:
    name: scaleway-prep-cancer-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:insta-credentials"
