---
{{ if has "handle_updates" .Values.features  }}
apiVersion: v1
kind: Service
metadata:
  name: update-handler
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cancer-update-handler
spec:
  revisionHistoryLimit: 0
  replicas: {{ if .Values.isEnabled }}1{{ else }}0{{ end }}
  minReadySeconds: 5
  serviceName: update-handler
  selector:
    matchLabels:
      app: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      volumes:
        - {{ include "secrets.volume" $ | fromYaml | toJson }}
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - handle_updates
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: 30m
            requests:
              cpu: 10m
              memory: 64Mi
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: base
          volumeMounts:
            - {{ include "secrets.volumeMount" . | fromYaml | toJson }}
{{- end }}
