{{ if has "handle_updates" .Values.features  }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-update-handler
spec:
  revisionHistoryLimit: 0
  replicas: {{ if .Values.isEnabled }}1{{ else }}0{{ end }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      volumes:
        - name: signaling
          emptyDir:
            sizeLimit: 1Mi
            medium: Memory
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - handle_updates
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 10m
              memory: 128Mi
          startupProbe:
            failureThreshold: 20
            exec:
              command: [ "test", "-f", "/var/run/bot/is-running"]
          env:
            - name: RUNNING_SIGNAL_FILE
              value: /var/run/bot/is-running
          envFrom:
            - secretRef:
                name: base
            - secretRef:
                name: nats
          volumeMounts:
            - mountPath: /var/run/bot
              name: signaling
{{- end }}
